### ISSUE TITLE
runtime error 

### ISSUE THREAD

**Issue by khizar1556** [kheldiente/spotify-equalizer#1]
Please help me to solve this issue
 android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class android.support.v7.widget.AppCompatCheckBox
        at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at midien.kheldiente.equalizer.adapter.PresetAdapter.onCreateViewHolder(PresetAdapter.kt:31)
        at midien.kheldiente.equalizer.adapter.PresetAdapter.onCreateViewHolder(PresetAdapter.kt:16)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3225)
        at android.view.View.measure(View.java:20195)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:20195)
        at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1450)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:516)
        at android.view.View.measure(View.java:20195)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:20195)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:20195)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:20195)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:20195)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:20195)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3094)
        at android.view.View.measure(View.java:20195)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2646)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1601)
    	at android.view.ViewRootImpl.performTrave

    <android.support.v7.widget.AppCompatCheckBox
        android:id="@+id/cb_preset_selected"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        style="@style/AppCheckBoxCompat"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        />

**Comment by kheldiente** [comment]
Did you change any values in style/AppCheckBoxCompat?

**Comment by kheldiente** [comment]
I suppose this issue is solved as there are no updates
